# Model setup
DAC.sample_rate: 48000
DAC.encoder_dim: 64
DAC.encoder_rates: [2, 4, 8, 8]
DAC.decoder_dim: 1536
DAC.decoder_rates: [8, 8, 4, 2]

# Quantization
DAC.n_codebooks: 8  #7.5kbps
DAC.codebook_size: 1024
DAC.codebook_dim: 8
DAC.quantizer_dropout: 0.5

# Discriminator
Discriminator.sample_rate: 48000
Discriminator.rates: []
Discriminator.periods: [2, 3, 5, 7, 11]
Discriminator.fft_sizes: [2048, 1024, 512]
Discriminator.bands:
  - [0.0, 0.1]
  - [0.1, 0.25]
  - [0.25, 0.5]
  - [0.5, 0.75]
  - [0.75, 1.0]

# Optimization
AdamW.betas: [0.8, 0.99]
AdamW.lr: 0.0001
ExponentialLR.gamma: 0.999996

amp: false
val_batch_size: 100
device: cuda
num_iters: 400000
save_iters: [10000, 50000, 100000, 150000, 200000, 250000, 300000, 350000, 400000]
valid_freq: 1000
sample_freq: 10000
num_workers: 32
val_idx: [0, 1, 2, 3, 4, 5, 6, 7]
seed: 0
lambdas:
  mel/loss: 15.0
  adv/feat_loss: 2.0
  adv/gen_loss: 1.0
  vq/commitment_loss: 0.25
  vq/codebook_loss: 1.0

VolumeNorm.db: [const, -16]

# Transforms
build_transform.preprocess:
  - Identity
build_transform.augment_prob: 0.0
build_transform.augment:
  - Identity
build_transform.postprocess:
  - VolumeNorm
  - RescaleAudio
  - ShiftPhase

# Loss setup
MultiScaleSTFTLoss.window_lengths: [2048, 512]
MelSpectrogramLoss.n_mels: [5, 10, 20, 40, 80, 160, 320]
MelSpectrogramLoss.window_lengths: [32, 64, 128, 256, 512, 1024, 2048]
MelSpectrogramLoss.mel_fmin: [0, 0, 0, 0, 0, 0, 0]
MelSpectrogramLoss.mel_fmax: [null, null, null, null, null, null, null]
MelSpectrogramLoss.pow: 1.0
MelSpectrogramLoss.clamp_eps: 1.0e-5
MelSpectrogramLoss.mag_weight: 0.0

# Data
batch_size: 12
train/AudioDataset.duration: 0.38 #最好能被prod整除
train/AudioDataset.n_examples: 100000

val/AudioDataset.duration: 5.0
val/build_transform.augment_prob: 1.0
val/AudioDataset.n_examples: 250

test/AudioDataset.duration: 10.0
test/build_transform.augment_prob: 1.0
test/AudioDataset.n_examples: 1000

AudioLoader.shuffle: true
AudioDataset.without_replacement: true

train/build_dataset.folders:
  libritts:
    - /home/Datasets/huiyu/FunCodec_LibriTTS/corpus/LibriTTS/train-clean-100/train_clean_100_newdir
    - /home/Datasets/huiyu/FunCodec_LibriTTS/corpus/LibriTTS/train-clean-360/train_clean_360_new
    - /home/Datasets/huiyu/FunCodec_LibriTTS/corpus/LibriTTS/train-other-500/LibriSpeech/train_other_500_newdir
    - /home/Datasets/huiyu/FunCodec_LibriTTS/corpus/LibriTTS/dev_all/dev_newdir
  codecsuperb:
    - /home/Datasets/huiyu/STL/arch0_gunshot_triangulation
    - /home/Datasets/huiyu/STL/arch1 
    - /home/Datasets/huiyu/STL/arch2_libri2mix 
    - /home/Datasets/huiyu/STL/fluent_speech_commands_dataset 
    - /home/Datasets/huiyu/STL/quesst14

  vctk:
    - /home/huiyu/download/dataset/audiodec/vctk/corpus/clean_trainset_84spk_wav

  # music_hq:
  #   - /data/musdb/train
  # music_uq:
  #   - /data/jamendo
  # general:
  #   - /data/audioset/data/unbalanced_train_segments/
  #   - /data/audioset/data/balanced_train_segments/

val/build_dataset.folders:
  val_speech:
    - /home/huiyu/download/dataset/audiodec/vctk/corpus/clean_validset_84spk_wav
  # music_hq:
  #   - /data/musdb/test
  # general:
  #   - /data/audioset/data/eval_segments/

test/build_dataset.folders:
  test_speech:
    - /home/huiyu/download/dataset/audiodec/vctk/corpus/clean_testset_wav
  # music_hq:
  #   - /data/musdb/test
  # general:
  #   - /data/audioset/data/eval_segments/
